CREATE TABLE ExampleAlter (
  Id INT64 NOT NULL,
  Col_1 INT64,
  Col_3 INT64,
) PRIMARY KEY(Id);

CREATE TABLE OutOfScope (
  IdA INT64 NOT NULL,
  Meta STRING(MAX),
) PRIMARY KEY(IdA);

CREATE TABLE ExampleRecreated (
  IdA INT64 NOT NULL,
  IdB INT64 NOT NULL,
  Meta STRING(MAX),
) PRIMARY KEY(IdA, IdB),
  INTERLEAVE IN PARENT OutOfScope ON DELETE NO ACTION;
