CREATE TABLE ExampleAlter (
  Id INT64 NOT NULL,
  Col_1 INT64 NOT NULL,
  Col_2 INT64,
  Col_3 STRING(MAX),
) PRIMARY KEY(Id);

CREATE TABLE OutOfScope (
  IdA INT64 NOT NULL,
  Meta STRING(MAX),
) PRIMARY KEY(IdA);

CREATE TABLE ExampleRecreated (
  IdA INT64 NOT NULL,
  IdB INT64 NOT NULL,
  IdC INT64 NOT NULL,
  Meta STRING(MAX),
) PRIMARY KEY(IdA, IdC),
  INTERLEAVE IN PARENT OutOfScope ON DELETE NO ACTION;

